/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-21 23:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.SQLException;
import java.io.IOException;
import banco.BD;
import controller.PessoaDao;

public final class actionCadastrojsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	System.out.println(request.getParameter("image"));
	String latlong = request.getParameter("teste");
	String lx = latlong.replace("(", "");
	String lat = null;
	String log = null;
	String ltlong = lx.replace(")", "");
	int tamanho = ltlong.length();
	for (int i = 0; i < tamanho; i++) {
		char v = ltlong.charAt(i);
		if (v == ',') {
			System.out.println(i);
			lat = ltlong.substring(0, i);
			log = ltlong.substring(i + 1, tamanho);
		}
	}

	double latitude = Double.parseDouble(lat);
	double longitude = Double.parseDouble(log);

	PessoaDao p = new PessoaDao();

	String nome = request.getParameter("nome");

	String email = request.getParameter("email");

	String telefone = request.getParameter("tel");

	String estado = request.getParameter("estado");

	String pais = request.getParameter("pais");

	String cidade = request.getParameter("cidade");


	String bairro = request.getParameter("bairro");

	String rua = request.getParameter("rua");

	String numero = (request.getParameter("num"));
	
	String senha = request.getParameter("senha");

	String confSenha = request.getParameter("Csenha");

	String cep = request.getParameter("cep");


	int t = 0;
	String tipo = null;
	BD bd = new BD();
	bd.getConnection();

	String pro = request.getParameter("profissao");
	System.out.println(pro);
	String sql = "select ID_categoria from categoria_prof where descricao = ?";
	try {
		bd.st = bd.con.prepareStatement(sql);

		bd.st.setString(1, pro);
		bd.rs = bd.st.executeQuery();
		bd.rs.next();
		tipo = bd.rs.getString("ID_categoria");
		t = Integer.parseInt(tipo);

	} catch (SQLException e) {
		// TODO Auto-generated catch block
		System.out.println(e.toString());
	}

	System.out.println("tipo" + tipo);

	p.setNome_razsocial(nome);
	p.setEmail(email);
	p.setTel_cel(telefone);
	p.setEstado(estado);
	p.setPais(pais);
	p.setCidade(cidade);
	p.setBairro(bairro);
	p.setRua(rua);
	p.setCep(cep);
	p.setNum(Integer.parseInt(numero));
	p.setSenha(senha);
	p.setLatitude(latitude);
	p.setLongitude(longitude);
	p.setID_categoria(t);
	p.setCod_tipo(2);
	
if(p.localizar(p.getEmail())){
	out.println("Email já cadastrado!");
	
}else{
	out.println(p.inserir());
}
	
	

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
