/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-30 15:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import banco.BD;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=800, user-scalable=no\">\r\n");
      out.write("        \r\n");
      out.write("        <title>PSearch</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/demo.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style1.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/inicioCss.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/component.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/component2.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/component3.css\" />\r\n");
      out.write("      \r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/modernizr.custom.86080.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("function AparecerDiv(){ // função aparecer\r\n");
      out.write("    document.getElementById('Modalbusca').style.display = \"block\";\r\n");
      out.write("    // usamos o style.display para manupular o css da div e mostrar ela\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function OcultarDiv(){  // função ocultar\r\n");
      out.write("    document.getElementById(\"Modalbusca\").style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("    // usamos o style.display para manupular o css da div e ocultar ela\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"cb-slideshow\">\r\n");
      out.write("            <li><span>Image 01</span></li>\r\n");
      out.write("            <li><span>Image 02</span></li>\r\n");
      out.write("            <li><span>Image 03</span></li>\r\n");
      out.write("            <li><span>Image 04</span></li>\r\n");
      out.write("            <li><span>Image 05</span></li>\r\n");
      out.write("            <li><span>Image 06</span></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"cabecalho\">\r\n");
      out.write("\r\n");
      out.write("        \t<img class=\"logo\" src=\"images/LogoBranco.png\">\r\n");
      out.write("        \t\r\n");
      out.write("            <button id=\"btni\" class=\"Btn Btn-2 Btn-2a\">Entrar</button>\r\n");
      out.write("\r\n");
      out.write("        \t\t<span id=\"saibamais\"><a class=\"saiba\"href=\"#\" >Saiba Mais</a></span>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"linha\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"conteudo\">\r\n");
      out.write("\r\n");
      out.write("                <button onclick=\"AparecerDiv()\" class=\"btn btn-6 btn-6b\" >Localizar Profissional</button>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    \t<div id=\"Modalbusca\">\r\n");
      out.write("        <div id=\"ModalCab\">\r\n");
      out.write("        \t<img class=\"modalImage\"src=\"images/ModalIcon.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    \t\t<form action=\"xmlcreate_map.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<input type=\"text\" class=\"textbox\" id=\"style\" name=\"address\" ><br/>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t\t\t\t\t<select name=\"profissao\" id=\"style2\" class=\"selectbox\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

					BD bd = new BD();
					bd.getConnection();
					String sql = "select descricao from categoria_prof";
					bd.st = bd.con.prepareStatement(sql);
					bd.rs = bd.st.executeQuery();
					while (bd.rs.next()) {

						out.println("<option value=" + bd.rs.getString("descricao")
								+ ">" + bd.rs.getString("descricao") + "</option>");
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</select>\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t   <button onclick=\"OcultarDiv()\" id=\"btnM\"class=\"Bttn Bttn-3 Bttn-3a\" action=\"xmlcreate_map.jsp\">Localizar</button>\r\n");
      out.write("    \t\t</form>\r\n");
      out.write("       \r\n");
      out.write("    \t</div>\r\n");
      out.write("            \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
