/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-30 16:30:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import banco.BD;

public final class map2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/component2.css\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Quicksand'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<script type=\"text/javascript\" src=\"_javascript/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"_css/map.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"_css/stars.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyDfmXMCQ3dfJKd_wAKe4Gh0_JmgJNKD_EY&sensor=SET_FALSE\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"_javascript/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction scrool() {\r\n");
      out.write("\t\tdocument.getElementById(\"ranking\").style.overflow = \"scroll\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction rodar() {\r\n");
      out.write("\t\tdocument.f.oculto.value = document.f.pro.value;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar geocoder;\r\n");
      out.write("\tvar map;\r\n");
      out.write("\r\n");
      out.write("\tfunction initialize() {\r\n");
      out.write("\t\tvar styles = [ {\r\n");
      out.write("\t\t\tstylers : [ {\r\n");
      out.write("\t\t\t\thue : \"#000099\"\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tsaturation : -30\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfeatureType : \"road\",\r\n");
      out.write("\t\t\telementType : \"geometry\",\r\n");
      out.write("\t\t\tstylers : [ {\r\n");
      out.write("\t\t\t\tlightness : 100\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tvisibility : \"simplified\"\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tfeatureType : \"road\",\r\n");
      out.write("\t\t\telementType : \"labels\",\r\n");
      out.write("\t\t\tstylers : [ {\r\n");
      out.write("\t\t\t\tvisibility : \"on\"\r\n");
      out.write("\t\t\t} ]\r\n");
      out.write("\t\t} ];\r\n");
      out.write("\r\n");
      out.write("\t\tvar styledMap = new google.maps.StyledMapType(styles, {\r\n");
      out.write("\t\t\tname : \"Styled Map\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tgeocoder = new google.maps.Geocoder();\r\n");
      out.write("\t\tvar latlng = new google.maps.LatLng(-34.397, 150.644);\r\n");
      out.write("\r\n");
      out.write("\t\tvar mapOptions = {\r\n");
      out.write("\t\t\tzoom : 16,\r\n");
      out.write("\t\t\tpanControl : false,\r\n");
      out.write("\t\t\tzoomControlOptions : {\r\n");
      out.write("\t\t\t\tstyle : google.maps.ZoomControlStyle.LARGE,\r\n");
      out.write("\t\t\t\tposition : google.maps.ControlPosition.LEFT_CENTER\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcenter : new google.maps.LatLng(-23.5505199, -46.63330939999997),\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tmap = new google.maps.Map(document.getElementById('conteudo'),\r\n");
      out.write("\t\t\t\tmapOptions);\r\n");
      out.write("\t\tmap.mapTypes.set('map_style', styledMap);\r\n");
      out.write("\t\tmap.setMapTypeId('map_style');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction codeAddress() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar address = document.getElementById('address').value;\r\n");
      out.write("\t\tgeocoder.geocode({\r\n");
      out.write("\t\t\t'address' : address\r\n");
      out.write("\t\t}, function(results, status) {\r\n");
      out.write("\t\t\tif (status == google.maps.GeocoderStatus.OK) {\r\n");
      out.write("\t\t\t\tmap.setCenter(results[0].geometry.location);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tmarker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\ticon : \"_img/iconuser.png\",\r\n");
      out.write("\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\tposition : results[0].geometry.location\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tgoogle.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t\t\t\t\tinfowindow.open(map, marker);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert('Erro ao obter coordenadas ' + status + geocoder);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadXMLFile() {\r\n");
      out.write("\t\tvar filename = 'pontos.xml';\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\turl : filename,\r\n");
      out.write("\t\t\tdataType : \"xml\",\r\n");
      out.write("\t\t\tsuccess : parseXML,\r\n");
      out.write("\t\t\terror : onXMLLoadFailed\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction onXMLLoadFailed() {\r\n");
      out.write("\t\t\talert(\"Ocorreu um erro durante a execução\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction parseXML(xml) {\r\n");
      out.write("\t\t\tvar markers = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar latlngbounds = new google.maps.LatLngBounds();\r\n");
      out.write("\t\t\tvar bounds = new google.maps.LatLngBounds();\r\n");
      out.write("\t\t\t$(xml)\r\n");
      out.write("\t\t\t\t\t.find(\"ocorrencia\")\r\n");
      out.write("\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar nme = $(this).find('Name').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar lat = $(this).find('Latitude').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar lng = $(this).find('Longitude').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar markerCoords = new google.maps.LatLng(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tparseFloat(lat), parseFloat(lng));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar rua = $(this).find('endereco').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar email = $(this).find('mail').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar tel = $(this).find('telefone').text();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar pro = $(this).find('Profissao').text();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar contentString = '<div id=\"iw-container\"><header id=\"divisoria\"></header><header class=\"iw-title\"><b >'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ nme\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \" - \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ pro\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</b></header><div  id=\"cont\" id=\"content\"><form  action=\"actionAvaliacao.jsp\" method=\"get\"> <table ></tr></td><tr><td  linhaspan=\"6\"></tr></td>'\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</td></tr><tr><td class=\"tabless\"><b>Endereço:</b> '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ rua\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</td></tr><tr><td class=\"tabless\"><b>Email:</b>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ email\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</tr></td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</td></tr><tr><td class=\"tabless\"><b>Telefone:</b>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ tel\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</tr></td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</td></tr><tr><td class=\"tabless\"><b>Média:</b>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</tr></td>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<tr><td class=\"tabless\"><input  style=\"display: none\" name=\"mailOculto\" value= '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ email\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '/></td></tr>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<tr><td class=\"tabless\"><input style=\"display: none\" name=\"nomelOculto\" value= '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ nme\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '></td></tr><tr><td></td></tr></table>'\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<fieldset class=\"rating\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" name=\"stars\" id=\"4_stars\" value=\"5\" >'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<label class=\"stars\" for=\"4_stars\">4 stars</label>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" name=\"stars\" id=\"3_stars\" value=\"4\" >'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<label class=\"stars\" for=\"3_stars\">3 stars</label>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" name=\"stars\" id=\"2_stars\" value=\"3\" >'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<label class=\"stars\" for=\"2_stars\">2 stars</label>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" name=\"stars\" id=\"1_stars\" value=\"2\" >'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<label class=\"stars\" for=\"1_stars\">1 star</label>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" name=\"stars\" id=\"0_stars\" value=\"1\" required>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<label class=\"stars\" for=\"0_stars\">0 star</label> '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input  type=\"submit\"  class=\"btnvotar\"  value= Avaliar>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</fieldset> '\r\n");
      out.write("\t\t\t\t\t\t\t\t'</form>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent : contentString,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tposition : markerCoords,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : nme,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticon : \"_img/proficon.png\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmap : map\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tgoogle.maps.event.addListener(marker, 'click',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tinfowindow.open(map, marker);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tgoogle.maps.event\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.addListener(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tinfowindow,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'domready',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Referência ao DIV que agrupa o fundo da infowindow\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar iw_outer = $('.gm-style-iw');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Referência ao DIV que agrupa o fundo da infowindow\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar iw_outer = $('.gm-style-iw');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Referencia aos DIV para os cantos e para a seta(cauda) da infowindow\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar iw_corners_tail = iw_outer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.prev();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Referência ao DIV que agrupa os elementos do botão fechar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar iw_btnClose = iw_outer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.next();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Retira o espaço da esquerda e do topo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tiw_outer.css({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tleft : '0',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttop : '0',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth : '100%'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Aplica 10px de raio para os cantos inferiores da sombra\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Altera a cor desejada para a sombra \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tiw_corners_tail\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t':nth-child(2)')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'border-bottom-left-radius' : '10px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'border-bottom-right-radius' : '10px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'background-color' : 'rgba(72, 181, 233, 0.4)'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Aplica 10px de raio para os cantos inferiores do fundo \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tiw_corners_tail\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.children(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t':nth-child(4)')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'border-bottom-left-radius' : '10px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'border-bottom-right-radius' : '10px'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t// Aplica o efeito desejado ao botão fechar\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tiw_btnClose\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.css({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\topacity : '1',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tright : '-12px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttop : '-12px',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder : '7px solid #D91E41',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'box-shadow' : '0 0 5px #3990B9'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tmap.setCenter(markerCoords);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction setDescPro() {\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tgoogle.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"loadXMLFile();\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"tudo\">\r\n");
      out.write("<header>\r\n");
      out.write("<input action=\"xmlcreate.jsp\" placeholder=\"Rua,estado,cidade\" id=\"address\"\r\n");
      out.write("\t\t\tclass=\"inputs\" type=\"text\" /> <input id=\"btloc\" class=\"button\"\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"Minha Localização\"\r\n");
      out.write("\t\t\tonclick=\"codeAddress()\" /> <input style=\"visibility: hidden\"\r\n");
      out.write("\t\t\ttype=\"text\" name=\"oculto\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<form id=\"formlocpro\" action=\"xmlcreate_map.jsp\" method=\"get\">\r\n");
      out.write("\t\t\t<select name=\"profissao\" class=\"combobox\" onchange=\"rodar()\">\r\n");
      out.write("\t\t\t\t<option value=\"ola mundo\">Selecione uma profissão</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					BD bd = new BD();
					bd.getConnection();
					String sql = "select descricao from categoria_prof ";
					bd.st = bd.con.prepareStatement(sql);
					bd.rs = bd.st.executeQuery();
					while (bd.rs.next()) {

						out.println("<option value=" + bd.rs.getString("descricao")
								+ ">" + bd.rs.getString("descricao") + "</option>");

					}
					bd.close();
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</select> <input id=\"btpro\" class=\"button\" type=\"submit\"\r\n");
      out.write("\t\t\t\tvalue=\"Localizar Profissionais\">\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t <input style=\"visibility: hidden\" action=\"map2.jsp\" method=\"get\"\r\n");
      out.write("\t\t\ttype='submit' value=\"localizar profissionais\" onclick=\"loadXMLFile();\">\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\t\t<header id=\"topo\"> <img src=\"images/logo.png\"></img>\r\n");
      out.write("\r\n");
      out.write("\t\t<button id=\"btne\" class=\"Btn Btn-2 Btn-2a\">Entrar</button>\r\n");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"linha\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<article id=\"conteudo\"> </article>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer id=\"rodape\"> <nav class=\"link\"> <a\r\n");
      out.write("\t\t\thref=\"index.html\">Início</a> <a href=\"estatisticas.html\">Estatísticas</a>\r\n");
      out.write("\t\t<a href=\"sobre_nos.html\">Sobre Nós</a> <a href=\"fale_conosco.html\">Fale\r\n");
      out.write("\t\t\tConosco</a> \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t</nav> </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
